(() => { "use strict"; const e = document.querySelector(".burgerBtn"), t = document.querySelector(".mobile_navigation_box"); e.addEventListener("click", (c => { e.classList.contains("active") ? (e.classList.remove("active"), t.classList.remove("active"), document.documentElement.style.overflow = "visible") : (e.classList.add("active"), t.classList.add("active"), document.documentElement.style.overflow = "hidden") })); let c = document.querySelector(".header"), s = 0; window.onresize = window.onscroll = function () { let t = document.documentElement.scrollTop; t > (window.innerWidth > 766 ? 80 : 50) && t > s && !e.classList.contains("active") ? c.classList.add("out") : c.classList.remove("out"), s = t }; const i = document.querySelectorAll(".desktop_navItemBtn"); for (let e = 0; e < i.length; e++)i[e].addEventListener("click", (t => { i[e].classList.toggle("active") })), window.addEventListener("click", (t => { if (i[e] !== t.target) return i[e].contains(t.target) ? (i[e].classList.add("active"), void i[e].lastElementChild.classList.add("active")) : (i[e].lastElementChild.classList.remove("active"), void i[e].classList.remove("active")); i[e].lastElementChild.classList.toggle("active") })); const n = document.querySelector('[href*="pages/merch"]'); window.location.pathname.includes("/merch/") ? n.remove() : n.nextElementSibling.remove(); const o = document.querySelector(".merchItemBox"); if (o) for (let e = 0; e < o.children.length; e++)o.children[e].addEventListener("click", (e => { e.stopPropagation(), o.classList.remove("active"), o.parentElement.classList.remove("active") })) })();
















































































































